# Generated by Django 5.1.9 on 2025-05-11 11:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
