# Generated by Django 5.1.9 on 2025-05-10 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.date(2025, 5, 10)),
        ),
    ]
