# Generated by Django 5.1.9 on 2025-05-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default='aa', upload_to='news/'),
            preserve_default=False,
        ),
    ]
