# Generated by Django 5.1.11 on 2025-09-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='brief_content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
