# Generated by Django 5.1.9 on 2025-05-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(default=123, max_length=16),
            preserve_default=False,
        ),
    ]
