# Generated by Django 5.1.9 on 2025-05-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_center', '0002_employee_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_done',
        ),
        migrations.AddField(
            model_name='order',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='date_scheduled',
            field=models.DateField(default='0001-01-01'),
            preserve_default=False,
        ),
    ]
