# Generated by Django 5.1.9 on 2025-05-12 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_center', '0003_remove_order_date_done_order_approved_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': {('can_approve', 'Can approve order (employees)'), ('can_create', 'Can create order (clients)')}},
        ),
    ]
