# Generated by Django 5.1.9 on 2025-05-12 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_center', '0004_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': {('client_perm', 'Can create order (clients)'), ('employee_perm', 'Can approve order (employees)')}},
        ),
    ]
