# Generated by Django 5.1.9 on 2025-05-13 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_center', '0008_alter_order_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='services',
        ),
        migrations.RemoveField(
            model_name='order',
            name='spare_parts',
        ),
        migrations.AddField(
            model_name='order',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='OrderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_center.order')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_center.service')),
            ],
        ),
        migrations.CreateModel(
            name='OrderSpareParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_center.order')),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_center.service')),
            ],
        ),
    ]
