# Generated by Django 5.1.9 on 2025-05-14 06:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_center', '0009_remove_order_services_remove_order_spare_parts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderservice',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_services', to='service_center.order'),
        ),
        migrations.AlterField(
            model_name='orderspareparts',
            name='number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='orderspareparts',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_spare_parts', to='service_center.order'),
        ),
    ]
