# Generated by Django 5.1.9 on 2025-05-14 06:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_center', '0010_alter_orderservice_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderservice',
            name='number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
