# Generated by Django 5.1.9 on 2025-05-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_center', '0011_alter_orderservice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='birth_date',
            field=models.DateField(default='0001-01-01'),
            preserve_default=False,
        ),
    ]
