# Generated by Django 5.1.9 on 2025-05-15 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_center', '0013_remove_employee_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_center.employee'),
        ),
    ]
