# Generated by Django 5.1.9 on 2025-05-15 16:29

import service_center.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_center', '0015_alter_order_date_scheduled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birth_date',
            field=models.DateField(validators=[service_center.models.validate_age_18]),
        ),
    ]
