# Generated by Django 5.1.9 on 2025-05-16 04:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_center', '0016_alter_client_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='boo', upload_to='employees/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('\\+375\\s?\\d{2}\\s?\\d{3}-?\\d{2}-?\\d{2}', message='Phone number should be +375 XX XXX-XX-XX')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('\\+375\\s?\\d{2}\\s?\\d{3}-?\\d{2}-?\\d{2}', message='Phone number should be +375 XX XXX-XX-XX')]),
        ),
    ]
