# Generated by Django 5.2.1 on 2025-05-16 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_center', '0017_employee_image_alter_client_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderspareparts',
            name='spare_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_center.sparepart'),
        ),
    ]
