# Generated by Django 5.1.9 on 2025-05-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_center', '0018_alter_orderspareparts_spare_part'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('discount', models.PositiveIntegerField()),
            ],
        ),
    ]
