# Generated by Django 5.1.11 on 2025-09-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_center', '0019_promocodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='specification',
            field=models.TextField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
