# Generated by Django 5.1.11 on 2025-09-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_center', '0020_employee_specification'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocodes',
            name='valid',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
