# Generated by Django 5.1.11 on 2025-09-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_center', '0021_promocodes_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
