# Generated by Django 5.1.11 on 2025-09-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_center', '0022_order_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
    ]
