# Generated by Django 5.1.11 on 2025-09-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_center', '0023_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='email',
            field=models.EmailField(default='smart-service@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='legal_address',
            field=models.TextField(default='123456, Moscow, Technical St., 15, office 20'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='logo_path',
            field=models.CharField(default='/MEDIA/icon.jpg', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='phone',
            field=models.CharField(default='+7 (495) 123-45-67', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='title',
            field=models.CharField(default='Smart-Service LTD', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='video_path',
            field=models.CharField(default='/MEDIA/video/repair.mp4', max_length=64),
            preserve_default=False,
        ),
    ]
