# Generated by Django 5.1.11 on 2025-09-08 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_center', '0024_about_description_about_email_about_legal_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='content',
        ),
    ]
