# Generated by Django 5.2.8 on 2025-11-16 13:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_center', '0027_alter_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='url',
            field=models.CharField(default='https://lms.bsuir.by/login/auth.php', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('((80\\d\\d|8 \\(0\\d\\d\\) )\\d{7}|\\+375 \\(\\d\\d\\) \\d{3}[- ]\\d{2}[- ]\\d{2})', message='Phone is invalid')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('((80\\d\\d|8 \\(0\\d\\d\\) )\\d{7}|\\+375 \\(\\d\\d\\) \\d{3}[- ]\\d{2}[- ]\\d{2})', message='Phone is invalid')]),
        ),
    ]
